name: ml-mw-mm
channels:
 - conda-forge
 - defaults
dependencies:
 - python==3.8.2
 - pandas
 - numpy
 - pip
 - pip:
    - pytest
    - isort
    - pre-commit
    - flake8
    - scikit-learn
    - imblearn
    - matplotlib
    - seaborn
    - neptune-client
    - neptune-notebooks
    - pickle
